dist: trusty
language: python
python:
- '3.5'
env:
  global:
    secure: EO6ezp7bFxG5aDuXYpc5dcUTElLBcMOdJv+RnZTooUD+DyscXeDtyuKe4BDPP3UnSlMGzn4xzwM+UDsncI2TNEE59Fly2TAZOnatbdZJjTyf9yap3NsS0eehlQnFsnmDrcoCe3ooeoJhhhKeqRUoga93wxCF/9SHdU7U/Gjv+XsBnbM+El1ufRheFNhubkV1bkrr+29FXmcFbC/678+41lDpRC815RAxnFeYlRLlp9My0EQYNyGnjKeAXgRyrDAX35AYKbDkt1rHwRnoFky9UuMy/wqcSxAPPWHyjqXMupvV7NQvXiqiVmVRide6S1yDo99CuP7NC6vIjE7aTE+XrnVmAp+RQ5tYpWS3xA+520Lpgi7ljRu7EwUMSnXn4WAxM8vbTQDZ1+49jny5eZ77AC8os8KtKQfEADRW3JB/1ujPWM9VimW1JlBRNV4VGs4BQ4fif79BLEwHF0YO0udjXSCAZ/oFu/a+r/ZLegYbDHgD7P+Ez6U5XzfprQuer5EVTuYxpkyQ623rNb+oVGpfVbsL9pQ1lh3XX0cbfp/JFrs+hcVzbM5NwiAXr5d/GPVxBJMryNEg0PyvKA3E+WRuwgKrj0G36gndIrOaGyvOJgNtwRVDtoEu0Us9Ii5j5IlmJZuaVFL0G6qDj1YLZ0VjQ4QVPEIL5fWm+teEqbP7bgU=
before_script:
- source version.sh
- wget https://github.com/gruntwork-io/fetch/releases/download/v0.1.1/fetch_linux_amd64
- chmod +x fetch_linux_amd64
- ./fetch_linux_amd64 --repo="https://github.com/RIAPS/riaps-externals/" --tag="$externalsversion" --release-asset="riaps-externals-armhf.deb" .
- ./fetch_linux_amd64 --repo="https://github.com/RIAPS/riaps-externals/" --tag=$externalsversion --release-asset="riaps-externals-amd64.deb" .
- ./fetch_linux_amd64 --repo="https://github.com/RIAPS/riaps-core" --tag=$coreversion --release-asset="riaps-core-amd64.deb" .
- ./fetch_linux_amd64 --repo="https://github.com/RIAPS/riaps-core" --tag=$coreversion --release-asset="riaps-core-armhf.deb" .
- ./fetch_linux_amd64 --repo="https://github.com/RIAPS/riaps-pycom" --tag=$pycomversion --release-asset="riaps-pycom-amd64.deb" .
- ./fetch_linux_amd64 --repo="https://github.com/RIAPS/riaps-pycom" --tag=$pycomversion --release-asset="riaps-pycom-armhf.deb" .
- ./fetch_linux_amd64 --repo="https://github.com/RIAPS/riaps-pycom" --tag=$pycomversion --release-asset="riaps-systemd-armhf.deb" .
- ./fetch_linux_amd64 --repo="https://github.com/RIAPS/riaps-pycom" --tag=$pycomversion --release-asset="riaps-systemd-amd64.deb" .
script:
- mkdir riaps-release
- cp riaps-externals-armhf.deb  riaps-externals-amd64.deb riaps-core-amd64.deb riaps-core-armhf.deb riaps-pycom-amd64.deb riaps-pycom-armhf.deb riaps-systemd-amd64.deb riaps-systemd-armhf.deb riaps-release/.
- echo "externalsversion=$externalsversion" >> riaps-release/manifest.txt
- echo "coreversion=$coreversion" >> riaps-release/manifest.txt
- echo "pycomversion=$pycomversion" >> riaps-release/manifest.txt
- tar cvzf riaps-release.tar.gz riaps-release
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: SeMxU38S60VIqCW/c3452ki5i0C8PdlR8pAja7lUU1kN8DE7sVvJAU8fxjGRNbFT+sCFlYKAJpd9i+ZUtZ9VKBS17Sr2eMdIYg1Ry7uqf7pnyiIWY7L9fYMJBewNXFw36MPl/ztKKjBGotF1o10F/+6C3WwZIFxU9ShYnJBjEHL6EV8H0QkqVKjlSl6h8U9c3mNf2B3AZhZLGVzgnR2Vctzt9ehpdPiPA46AC0b7vYf0GI6YeHYDG2PSNT/cCDmRkYLdutAA9R3VmxN3W+QoOI6ls2eZquUsLi4NnHmcaSTWNHxI66L2uXBROZftXQbyKUYZH10uPjBU64w3hstaiIfUw0gNRQ+DFvtUQtNjfXIY/DhWwA5WUvRN1mVDzHc3+8MpawtY9jC0vT+BQ4eE51K5/fGH0A0xAraeUbrfexRJBiP5EMqzWdMYRGNrwzuDneK82L4+g8z8cg20Y/ngtbbi3B2V86NHO6g3okMm0yDd0WLrnd2S7bWeEoxZHwecbeII2ReU1K04xj7QLXrKPye1YvCJyuh7Fb4S0blK+P095/oD0RwTImuM8lteaAf+sxr8qLRkBF3sKiZRXfpJRJS5ugo5zui5MYdakkmBmpSdA6Ajtkfn/esjr268QNmaFCpFkPtX8vDXsOy6U2b5QOCwRwnUFh63EZazntGyATA=
  file: riaps-release.tar.gz
  skip_cleanup: true
  on:
    tags: true
